package lib
/**
  主要封装的是连接操作
 */
import (
	"time"
	"container/list"
	"sync"
	"net"
	"fmt"
)

type Connection struct {
	conn   interface{}         //连接对象
	closed int32

	forbidden int32             //是否被禁言
	notification_on bool        //桌面在线时是否通知手机端
	online bool

	//客户端协议版本号
	version int

	tm     time.Time
	appid  int64
	uid    int64
	device_id string
	device_ID int64 //generated by device_id + platform_id
	platform_id int8

	messages *list.List //待发送的消息队列 FIFO
	mutex  sync.Mutex
}

//发送消息
func (client *Connection) read() *Message {
	fmt.Println("执行connection的 read的方法")
	if conn, ok := client.conn.(net.Conn); ok {
		return ReceiveClientMessage(conn)
	}
	return nil
}

//链接关闭
func (client *Connection) close() {
	if conn, ok := client.conn.(net.Conn); ok {
		conn.Close()
	}
}